// <auto-generated />
namespace Spa_Resort_bali.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Removed2FA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removed2FA));
        
        string IMigrationMetadata.Id
        {
            get { return "201909051818344_Removed2FA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
