//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Resort_bali.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int BookingId { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public string UserId { get; set; }
        public string Description { get; set; }
        public int LodgeId { get; set; }
        public int Discount { get; set; }
        public decimal Price { get; set; }
        public bool Canceled { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Lodges Lodges { get; set; }
    }
}
