//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Resort_bali.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LodgePrice
    {
        public System.DateTime StartingDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public decimal price { get; set; }
        public int LodgeTypeId { get; set; }
    
        public virtual LodgeTypes LodgeTypes { get; set; }
    }
}
