//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Resort_bali.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LodgeTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LodgeTypes()
        {
            this.Lodges = new HashSet<Lodges>();
            this.LodgePrice = new HashSet<LodgePrice>();
        }
    
        public int LodgeTypeId { get; set; }
        public string Name { get; set; }
        public int Surface { get; set; }
        public string Description { get; set; }
        public int MaxPersons { get; set; }
        public byte[] Picture { get; set; }
        public bool Disabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lodges> Lodges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LodgePrice> LodgePrice { get; set; }
    }
}
