//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spa_Resort_bali.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Spa_Resort_Bali_DatabaseEntities : DbContext
    {
        public Spa_Resort_Bali_DatabaseEntities()
            : base("name=Spa_Resort_Bali_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Bookings> Bookings { get; set; }
        public virtual DbSet<Lodges> Lodges { get; set; }
        public virtual DbSet<LodgeTypes> LodgeTypes { get; set; }
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<LodgePrice> LodgePrice { get; set; }
    
        public virtual ObjectResult<Nullable<double>> spGetDiscount(Nullable<System.DateTime> cHECKINDATE)
        {
            var cHECKINDATEParameter = cHECKINDATE.HasValue ?
                new ObjectParameter("CHECKINDATE", cHECKINDATE) :
                new ObjectParameter("CHECKINDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("spGetDiscount", cHECKINDATEParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> spGetLodgePrice(Nullable<System.DateTime> cHECKINDATE, string lODGECODE)
        {
            var cHECKINDATEParameter = cHECKINDATE.HasValue ?
                new ObjectParameter("CHECKINDATE", cHECKINDATE) :
                new ObjectParameter("CHECKINDATE", typeof(System.DateTime));
    
            var lODGECODEParameter = lODGECODE != null ?
                new ObjectParameter("LODGECODE", lODGECODE) :
                new ObjectParameter("LODGECODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("spGetLodgePrice", cHECKINDATEParameter, lODGECODEParameter);
        }
    }
}
